import type { MnaItem } from "./marketIntelFeed";

/**
 * A frozen review set of real life-sciences transactions. These records are
 * intentionally static in mock mode, and every item links to the announcing
 * company's original release rather than a generated destination.
 */
export const FROZEN_MARKET_INTEL_DEALS: MnaItem[] = [
  {
    acquirer: "Amneal Pharmaceuticals",
    target: "Kashiv BioSciences",
    status: "completed",
    division: "Medicinal Products",
    valueLabel: null,
    date: "2026-08-10T12:00:00Z",
    summary: "Amneal completed its acquisition of Kashiv BioSciences, expanding its biosimilars development and manufacturing platform.",
    sourceLabel: "Amneal Pharmaceuticals",
    sourceUrl: "https://investors.amneal.com/news/press-releases/press-release-details/2026/Amneal-Completes-Acquisition-of-Kashiv-BioSciences-Creating-a-Global-Biosimilar-Leader/default.aspx",
  },
  {
    acquirer: "Johnson & Johnson",
    target: "Firefly Bio",
    status: "completed",
    division: "Medicinal Products",
    valueLabel: "$1B",
    date: "2026-07-29T12:00:00Z",
    summary: "Johnson & Johnson completed its acquisition of Firefly Bio to add its degrader-antibody conjugate platform to the oncology pipeline.",
    sourceLabel: "Johnson & Johnson",
    sourceUrl: "https://www.jnj.com/media-center/press-releases/johnson-johnson-completes-acquisition-of-firefly-bio-inc-to-advance-next-generation-oncology-innovation",
  },
  {
    acquirer: "Merck KGaA",
    target: "Bio-Techne",
    status: "announced",
    division: "Medical Devices",
    valueLabel: "$11.3B",
    date: "2026-06-25T12:00:00Z",
    summary: "Merck KGaA agreed to acquire Bio-Techne to expand its life-science tools and multi-omics portfolio.",
    sourceLabel: "Bio-Techne",
    sourceUrl: "https://investors.bio-techne.com/all-sec-filings/content/0001999371-26-013429/ex99-1.htm",
  },
  {
    acquirer: "Chiesi Group",
    target: "KalVista Pharmaceuticals",
    status: "announced",
    division: "Medicinal Products",
    valueLabel: "$1.9B",
    date: "2026-04-29T12:00:00Z",
    summary: "Chiesi agreed to acquire KalVista Pharmaceuticals, adding an oral hereditary angioedema treatment to its rare-disease portfolio.",
    sourceLabel: "Chiesi Group",
    sourceUrl: "https://www.chiesi.com/en/media-hub/press-releases/chiesi-group-to-acquire-kalVista-pharmaceuticals-expanding-its-global-rare-disease-portfolio",
  },
  {
    acquirer: "QIAGEN",
    target: "Parse Biosciences",
    status: "announced",
    division: "Medical Devices",
    valueLabel: "$225M",
    date: "2025-11-04T12:00:00Z",
    summary: "QIAGEN agreed to acquire Parse Biosciences to expand its sample-technologies portfolio into scalable single-cell analysis.",
    sourceLabel: "QIAGEN",
    sourceUrl: "https://corporate.qiagen.com/English/newsroom/press-releases/press-release-details/2025/QIAGEN-to-acquire-Parse-Biosciences-expanding-its-Sample-technologies-portfolio-into-highly-scalable-single-cell-solutions/",
  },
  {
    acquirer: "Siemens",
    target: "Dotmatics",
    status: "completed",
    division: "Medical Devices",
    valueLabel: "$5.1B",
    date: "2025-07-01T12:00:00Z",
    summary: "Siemens completed its acquisition of Dotmatics, adding scientific software for life-sciences research and development.",
    sourceLabel: "Siemens",
    sourceUrl: "https://press.siemens.com/global/en/pressrelease/siemens-completes-acquisition-dotmatics",
  },
  {
    acquirer: "Sanofi",
    target: "Vigil Neuroscience",
    status: "announced",
    division: "Medicinal Products",
    valueLabel: null,
    date: "2025-05-21T12:00:00Z",
    summary: "Sanofi agreed to acquire Vigil Neuroscience to strengthen its neurology pipeline with a program targeting Alzheimer's disease.",
    sourceLabel: "Sanofi",
    sourceUrl: "https://www.sanofi.com/en/media-room/press-releases/2025/2025-05-21-23-15-31-3086232",
  },
  {
    acquirer: "Lupin",
    target: "Renascience",
    status: "completed",
    division: "Medicinal Products",
    valueLabel: null,
    date: "2025-04-01T12:00:00Z",
    summary: "Lupin acquired Renascience to strengthen its specialty-pharma business in the United Kingdom.",
    sourceLabel: "Lupin Healthcare",
    sourceUrl: "https://www.lupinhealthcare.co.uk/wp-content/uploads/2025/05/Press_Release_Lupin_Acquisition_Renascience_UK-UK-RESP-2503-00002.pdf",
  },
  {
    acquirer: "Novartis",
    target: "Avidity Biosciences",
    status: "announced",
    division: "Medicinal Products",
    valueLabel: null,
    date: "2025-01-01T12:00:00Z",
    summary: "Novartis agreed to acquire Avidity Biosciences, strengthening its neuroscience pipeline with RNA therapeutics.",
    sourceLabel: "Novartis",
    sourceUrl: "https://www.novartis.com/news/media-releases/novartis-agrees-acquire-avidity-biosciences-innovator-rna-therapeutics-strengthening-its-late-stage-neuroscience-pipeline",
  },
];
