/**
 * THE FILES THAT SHIP WITH THE APP.
 *
 * Anir, Aug 28: "show me what it would look like with documents. Obviously,
 * you don't need the actual documents, but in Mock-mode I need to see."
 *
 * Mock's documents were filenames with nothing behind them: the row refused
 * the click and the hover card had nothing to render, which is the opposite of
 * seeing what it looks like. A sample document now points at a real file that
 * ships in `public/sample-documents`, generated by
 * `scripts/build-sample-documents.mjs`.
 *
 * WHY A SCHEME RATHER THAN A PATH. A stored `docsPath` addresses Freya.Docs,
 * and anything that reads one is reading a customer's file. `sample-doc:` can
 * never be mistaken for one, so a route either recognises it and serves a
 * committed demo file, or treats it as storage — never both.
 *
 * These files describe the app's own fictional cast (Cortexa, Helix, Aether,
 * Quantum). Nothing here is about a real Freyr customer.
 */

const SCHEME = "sample-doc:";
const DIRECTORY = "/sample-documents/";

/** Every file that exists, so a typo cannot become a 404 in front of Suren. */
export const SAMPLE_DOCUMENT_FILES = [
  "cmc-writing-approach.pdf",
  "helix-capability-deck.pdf",
  "publishing-workflow-one-pager.pdf",
  "q3-review-pack.pdf",
  "eu-mdr-discovery-questions.docx",
  "delivery-metrics.xlsx",
] as const;

export type SampleDocumentFile = (typeof SAMPLE_DOCUMENT_FILES)[number];

/** The docsPath a sample record carries. */
export function sampleDocPath(file: SampleDocumentFile): string {
  return `${SCHEME}${file}`;
}

export function isSampleDocPath(docsPath: string | undefined | null): boolean {
  return typeof docsPath === "string" && docsPath.startsWith(SCHEME);
}

/**
 * Where the browser reads it from — a static file, so it needs no signed URL
 * and no storage account. Null when the path is not a sample one, or names a
 * file that is not in the shipped set.
 */
export function sampleDocUrl(docsPath: string | undefined | null): string | null {
  if (!isSampleDocPath(docsPath)) return null;
  const file = (docsPath as string).slice(SCHEME.length);
  return (SAMPLE_DOCUMENT_FILES as readonly string[]).includes(file)
    ? `${DIRECTORY}${file}`
    : null;
}
