// Offering-category voice agents (Suren, Jul 3) — one ElevenLabs agent per
// offering category, created on the proven XP stack (see lib/voiceAgents.json,
// generated by the setup script). Everything is WIRED; actually dialing waits
// for the last step — buying + connecting a Twilio number (deliberately last,
// per Anir, so nothing is spent until the rest is verified). Until then calls
// land in a queue with an honest status.

import { hasElevenLabs } from "./env";
import type { Contact, Customer } from "./types";
import type { Offering } from "./offerings";
import agentIds from "./voiceAgents.json";

export type VoiceCallStatus = "called" | "waiting_for_number" | "no_agent";

export interface VoiceCall {
  id: string;
  contact_id: string;
  contact_name: string;
  company: string;
  offering_id: string | null;
  offering_name: string; // or the category for bulk runs
  category: string;
  agent_id: string | null;
  status: VoiceCallStatus;
  reason?: string;
  created_at: string;
}

interface VoiceStore {
  queue: VoiceCall[];
}

function store(): VoiceStore {
  const g = globalThis as typeof globalThis & { __freyrVoice?: VoiceStore };
  if (!g.__freyrVoice) g.__freyrVoice = { queue: [] };
  return g.__freyrVoice;
}

export function agentForCategory(category: string): string | null {
  return (agentIds as Record<string, string>)[category] || null;
}

export function voiceStatus() {
  return {
    wired: hasElevenLabs(),
    phoneConnected: !!process.env.ELEVENLABS_PHONE_NUMBER_ID,
    agents: agentIds as Record<string, string>,
    queued: store().queue.filter((q) => q.status === "waiting_for_number").length,
  };
}

let n = 0;
const uid = () => `vc-${Date.now().toString(36)}-${n++}`;

// Place the call when the stack is fully connected; otherwise queue it with an
// honest reason. Never silently pretends a call happened.
export async function placeOrQueueCall(opts: {
  contact: Contact;
  customer: Customer | null;
  offering: Offering | null; // null for bulk category runs
  category: string;
}): Promise<VoiceCall> {
  const { contact, customer, offering, category } = opts;
  const agent_id = agentForCategory(category);
  const phoneId = process.env.ELEVENLABS_PHONE_NUMBER_ID;
  const live =
    hasElevenLabs() && process.env.AGENT_FORCE_MOCK !== "1" && !!phoneId;

  const entry: VoiceCall = {
    id: uid(),
    contact_id: contact.id,
    contact_name: contact.full_name,
    company: customer?.company_name || "",
    offering_id: offering?.id || null,
    offering_name: offering?.offering_name || category,
    category,
    agent_id,
    status: "waiting_for_number",
    created_at: new Date().toISOString(),
  };

  if (!agent_id) {
    entry.status = "no_agent";
    entry.reason = `No voice agent for "${category}" yet.`;
  } else if (live && contact.phone) {
    try {
      const { outboundCall } = await import("./elevenlabs");
      const ok = await outboundCall(agent_id, phoneId!, contact.phone);
      if (ok) {
        entry.status = "called";
      } else {
        entry.reason = "Dial failed — left in the queue.";
      }
    } catch {
      entry.reason = "Dial failed — left in the queue.";
    }
  } else if (live && !contact.phone) {
    entry.reason = "No phone number on this contact yet.";
  } else {
    entry.reason = phoneId
      ? "Voice is mocked in this environment."
      : "Connect a phone number to start dialing.";
  }

  store().queue.unshift(entry);
  return entry;
}

export function listVoiceQueue(): VoiceCall[] {
  return store().queue;
}
