// Offering-category voice agents (Suren, Jul 3) — one ElevenLabs agent per
// offering category, created on the proven XP stack (see lib/voiceAgents.json,
// generated by the setup script). Everything is WIRED; actually dialing waits
// for the last step — buying + connecting a Twilio number (deliberately last,
// per Anir, so nothing is spent until the rest is verified). Until then calls
// land in a queue with an honest status.

import { hasElevenLabs } from "./env";
import type { Contact, Customer } from "./types";
import type { Offering } from "./offerings";
import agentIds from "./voiceAgents.json";

export type VoiceCallStatus = "called" | "waiting_for_number" | "no_agent";

// How a finished call ended — filled by ElevenLabs conversation results once
// the number is live; seeded with sample values so the analytics render now.
export type VoiceOutcome = "interested" | "follow_up" | "no_answer" | "declined";

export interface VoiceCall {
  id: string;
  contact_id: string;
  contact_name: string;
  company: string;
  offering_id: string | null;
  offering_name: string; // or the category for bulk runs
  category: string;
  agent_id: string | null;
  status: VoiceCallStatus;
  reason?: string;
  outcome?: VoiceOutcome | null;
  duration_secs?: number | null;
  created_at: string;
}

interface VoiceStore {
  queue: VoiceCall[];
}

// Sample completed calls (Anir, Jul 3: "for the voice agent stuff I want to
// see all of the statistics — conversations, scores, graphs") — the same
// seeded contacts as the rest of the app, so campaign cross-links resolve.
// Runtime calls queue on top with honest statuses; these give the analytics
// their shape until the phone number connects.
function seedCalls(): VoiceCall[] {
  const d = (days: number) =>
    new Date(Date.now() - days * 86_400_000).toISOString();
  const call = (
    id: string,
    contact: [string, string, string], // id, name, company
    category: string,
    offering: string,
    status: VoiceCallStatus,
    outcome: VoiceOutcome | null,
    duration: number | null,
    days: number
  ): VoiceCall => ({
    id,
    contact_id: contact[0],
    contact_name: contact[1],
    company: contact[2],
    offering_id: null,
    offering_name: offering,
    category,
    agent_id: agentForCategory(category),
    status,
    outcome,
    duration_secs: duration,
    created_at: d(days),
  });
  return [
    call("vc-seed-01", ["cont-004", "Dr. Lena Vogt", "Helix Biologics"], "Labeling and Artwork", "Labeling and Artwork", "called", "interested", 284, 1),
    call("vc-seed-02", ["cont-005", "Prithvi Nair", "Solvance Pharma"], "Submissions and Document Operations", "Submissions and Document Operations", "called", "follow_up", 196, 1.2),
    call("vc-seed-03", ["cont-012", "Dr. Hana Kim", "Orion Vaccines"], "Global Regulatory Intelligence", "Global Regulatory Intelligence", "called", "interested", 233, 2),
    call("vc-seed-04", ["cont-003", "Marcus Thorne", "Cortexa Biopharma"], "Regulatory Affairs", "Regulatory Affairs", "called", "follow_up", 172, 2.5),
    call("vc-seed-05", ["cont-010", "Claudia Hofmann", "Meridian Pharmaceuticals"], "Regulatory Information Management", "Regulatory Information Management", "called", "declined", 58, 3),
    call("vc-seed-06", ["cont-007", "Stefan Bauer", "Aether Medical Devices"], "Global Regulatory Intelligence", "Global Regulatory Intelligence", "called", "no_answer", 0, 3.4),
    call("vc-seed-07", ["cont-011", "Owen Bradley", "Northwind Biosciences"], "Regulatory Affairs", "Regulatory Affairs", "waiting_for_number", null, null, 0.3),
    call("vc-seed-08", ["cont-008", "Megan Ruiz", "Solara Consumer Health"], "Labeling and Artwork", "Labeling and Artwork", "waiting_for_number", null, null, 0.5),
  ];
}

function store(): VoiceStore {
  const g = globalThis as typeof globalThis & { __freyrVoice?: VoiceStore };
  if (!g.__freyrVoice) g.__freyrVoice = { queue: seedCalls() };
  return g.__freyrVoice;
}

export function agentForCategory(category: string): string | null {
  return (agentIds as Record<string, string>)[category] || null;
}

export function voiceStatus() {
  // In FORCE_MOCK (the test env) the stack genuinely won't dial even with a
  // number configured, so "connected" would be a lie there.
  const mock = process.env.AGENT_FORCE_MOCK === "1";
  return {
    wired: hasElevenLabs(),
    phoneConnected: !mock && !!process.env.ELEVENLABS_PHONE_NUMBER_ID,
    phoneNumber: (!mock && process.env.FREYR_VOICE_NUMBER) || null,
    agents: agentIds as Record<string, string>,
    queued: store().queue.filter((q) => q.status === "waiting_for_number").length,
  };
}

let n = 0;
const uid = () => `vc-${Date.now().toString(36)}-${n++}`;

// Place the call when the stack is fully connected; otherwise queue it with an
// honest reason. Never silently pretends a call happened.
export async function placeOrQueueCall(opts: {
  contact: Contact;
  customer: Customer | null;
  offering: Offering | null; // null for bulk category runs
  category: string;
}): Promise<VoiceCall> {
  const { contact, customer, offering, category } = opts;
  const agent_id = agentForCategory(category);
  const phoneId = process.env.ELEVENLABS_PHONE_NUMBER_ID;
  const live =
    hasElevenLabs() && process.env.AGENT_FORCE_MOCK !== "1" && !!phoneId;

  const entry: VoiceCall = {
    id: uid(),
    contact_id: contact.id,
    contact_name: contact.full_name,
    company: customer?.company_name || "",
    offering_id: offering?.id || null,
    offering_name: offering?.offering_name || category,
    category,
    agent_id,
    status: "waiting_for_number",
    created_at: new Date().toISOString(),
  };

  if (!agent_id) {
    entry.status = "no_agent";
    entry.reason = `No voice agent for "${category}" yet.`;
  } else if (live && contact.phone) {
    try {
      const { outboundCall } = await import("./elevenlabs");
      // Pass who we're calling + what to pitch — the agent opens with the
      // prospect's name and the right offering (dynamic variables).
      const ok = await outboundCall(agent_id, phoneId!, contact.phone, {
        contact_name: contact.full_name,
        company: customer?.company_name || undefined,
        offering: offering?.offering_name || category,
      });
      if (ok) {
        entry.status = "called";
      } else {
        entry.reason = "Dial failed — left in the queue.";
      }
    } catch {
      entry.reason = "Dial failed — left in the queue.";
    }
  } else if (live && !contact.phone) {
    entry.reason = "No phone number on this contact yet.";
  } else {
    entry.reason = phoneId
      ? "Voice is mocked in this environment."
      : "Connect a phone number to start dialing.";
  }

  store().queue.unshift(entry);
  return entry;
}

export function listVoiceQueue(): VoiceCall[] {
  return store().queue;
}
